apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: marsupial-nodejs 
  janus-idp.io/tekton: marsupial-nodejs
  backstage.io/kubernetes-id: marsupial-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: marsupial-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  